Merge 2.x into main
opensearch-project/asynchronous-search pull request #195
Opened 2022-10-31 13:59 UTC by Arpit-Bandejiya

Updating the main branch with the changes in 2.x branch

2022-11-01 12:18 UTC, bharath-techie approved these changes

2022-11-01 14:50 UTC, bharath-techie requested changes
lets remove release notes for now and add it as part of separate pr

2022-11-02 09:07 UTC, bharath-techie approved these changes

2022-11-02 10:18 UTC, dhruv16dhr approved these changes

2022-11-02 10:18 UTC, merged